apiVersion: 1

datasources:
  - name: Local PostgreSQL
    uid: sentinel-postgres
    type: postgres
    access: proxy
    url: localhost:5432
    database: sentinel_db
    user: postgres
    secureJsonData:
      password: localpassword
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
