apiVersion: 1

datasources:
  - name: Supabase PostgreSQL
    type: postgres
    access: proxy
    url: db.hnpndjvwniidhyhhhchz.supabase.co:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: yXDNi9v6JGkvBfSE
    jsonData:
      sslmode: require
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: true
